<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Sphere.Basket\Sphere.Basket.csproj" />
    <ProjectReference Include="..\Modules\Sphere.Catalog\Sphere.Catalog.csproj" />
    <ProjectReference Include="..\Modules\Sphere.Ordering\Sphere.Ordering.csproj" />
  </ItemGroup>

</Project>
